version: 0.2

phases:
  install:
    commands:
      - echo "Instalando httpd"
      - yum install -y httpd

  build:
    commands:
      - echo "Construyendo aplicación"
      - echo "<html><body><h1>Hola Mundo</h1></body></html>" > /var/www/html/index.html

  post_build:
    commands:
      - echo "Iniciando servidor web"
      - systemctl start httpd
      - systemctl enable httpd

artifacts:
  files:
    - /var/www/html/index.html
